//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdinLib.EdinServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://soap.edi.service.org", ConfigurationName="EdinServiceReference.ServiceWs")]
    public interface ServiceWs {
        
        // CODEGEN: Generating message contract since the operation getDocuments is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EdinLib.EdinServiceReference.getDocumentsResponse1 getDocuments(EdinLib.EdinServiceReference.getDocumentsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EdinLib.EdinServiceReference.getDocumentsResponse1> getDocumentsAsync(EdinLib.EdinServiceReference.getDocumentsRequest1 request);
        
        // CODEGEN: Generating message contract since the operation uploadDoc is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EdinLib.EdinServiceReference.uploadDocResponse1 uploadDoc(EdinLib.EdinServiceReference.uploadDocRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EdinLib.EdinServiceReference.uploadDocResponse1> uploadDocAsync(EdinLib.EdinServiceReference.uploadDocRequest1 request);
        
        // CODEGEN: Generating message contract since the operation archiveDocuments is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EdinLib.EdinServiceReference.archiveDocumentsResponse1 archiveDocuments(EdinLib.EdinServiceReference.archiveDocumentsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EdinLib.EdinServiceReference.archiveDocumentsResponse1> archiveDocumentsAsync(EdinLib.EdinServiceReference.archiveDocumentsRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EdinLib.EdinServiceReference.getListResponse1 getList(EdinLib.EdinServiceReference.getListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EdinLib.EdinServiceReference.getListResponse1> getListAsync(EdinLib.EdinServiceReference.getListRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getDoc is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EdinLib.EdinServiceReference.getDocResponse1 getDoc(EdinLib.EdinServiceReference.getDocRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EdinLib.EdinServiceReference.getDocResponse1> getDocAsync(EdinLib.EdinServiceReference.getDocRequest1 request);
        
        // CODEGEN: Generating message contract since the operation archiveDoc is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EdinLib.EdinServiceReference.archiveDocResponse1 archiveDoc(EdinLib.EdinServiceReference.archiveDocRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EdinLib.EdinServiceReference.archiveDocResponse1> archiveDocAsync(EdinLib.EdinServiceReference.archiveDocRequest1 request);
        
        // CODEGEN: Generating message contract since the operation sendDoc is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EdinLib.EdinServiceReference.sendDocResponse1 sendDoc(EdinLib.EdinServiceReference.sendDocRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EdinLib.EdinServiceReference.sendDocResponse1> sendDocAsync(EdinLib.EdinServiceReference.sendDocRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.service.org")]
    public partial class getDocumentsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediLogin userField;
        
        private string[] fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediLogin user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fileName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string[] fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.edi.service.org")]
    public partial class ediLogin : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string passField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string pass {
            get {
                return this.passField;
            }
            set {
                this.passField = value;
                this.RaisePropertyChanged("pass");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ediFileList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ediFile))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.edi.service.org")]
    public partial class ediResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.edi.service.org")]
    public partial class ediFileList : ediResponse {
        
        private string[] listField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("list", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] list {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
                this.RaisePropertyChanged("list");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soap.edi.service.org")]
    public partial class ediFile : ediResponse {
        
        private byte[] contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.service.org")]
    public partial class getDocumentsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediFile resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediFile result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocumentsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.service.org", Order=0)]
        public EdinLib.EdinServiceReference.getDocumentsRequest getDocumentsRequest;
        
        public getDocumentsRequest1() {
        }
        
        public getDocumentsRequest1(EdinLib.EdinServiceReference.getDocumentsRequest getDocumentsRequest) {
            this.getDocumentsRequest = getDocumentsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocumentsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.service.org", Order=0)]
        public EdinLib.EdinServiceReference.getDocumentsResponse getDocumentsResponse;
        
        public getDocumentsResponse1() {
        }
        
        public getDocumentsResponse1(EdinLib.EdinServiceReference.getDocumentsResponse getDocumentsResponse) {
            this.getDocumentsResponse = getDocumentsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.service.org")]
    public partial class uploadDocRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediLogin userField;
        
        private string fileNameField;
        
        private byte[] contentField;
        
        private string remoteFolderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediLogin user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true, Order=2)]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string remoteFolder {
            get {
                return this.remoteFolderField;
            }
            set {
                this.remoteFolderField = value;
                this.RaisePropertyChanged("remoteFolder");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.service.org")]
    public partial class uploadDocResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediResponse resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediResponse result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadDocRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.service.org", Order=0)]
        public EdinLib.EdinServiceReference.uploadDocRequest uploadDocRequest;
        
        public uploadDocRequest1() {
        }
        
        public uploadDocRequest1(EdinLib.EdinServiceReference.uploadDocRequest uploadDocRequest) {
            this.uploadDocRequest = uploadDocRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class uploadDocResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.service.org", Order=0)]
        public EdinLib.EdinServiceReference.uploadDocResponse uploadDocResponse;
        
        public uploadDocResponse1() {
        }
        
        public uploadDocResponse1(EdinLib.EdinServiceReference.uploadDocResponse uploadDocResponse) {
            this.uploadDocResponse = uploadDocResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.service.org")]
    public partial class archiveDocumentsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediLogin userField;
        
        private string[] fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediLogin user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fileName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string[] fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.service.org")]
    public partial class archiveDocumentsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediResponse resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediResponse result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class archiveDocumentsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.service.org", Order=0)]
        public EdinLib.EdinServiceReference.archiveDocumentsRequest archiveDocumentsRequest;
        
        public archiveDocumentsRequest1() {
        }
        
        public archiveDocumentsRequest1(EdinLib.EdinServiceReference.archiveDocumentsRequest archiveDocumentsRequest) {
            this.archiveDocumentsRequest = archiveDocumentsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class archiveDocumentsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.service.org", Order=0)]
        public EdinLib.EdinServiceReference.archiveDocumentsResponse archiveDocumentsResponse;
        
        public archiveDocumentsResponse1() {
        }
        
        public archiveDocumentsResponse1(EdinLib.EdinServiceReference.archiveDocumentsResponse archiveDocumentsResponse) {
            this.archiveDocumentsResponse = archiveDocumentsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.service.org")]
    public partial class getListRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediLogin userField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediLogin user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.service.org")]
    public partial class getListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediFileList resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediFileList result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.service.org", Order=0)]
        public EdinLib.EdinServiceReference.getListRequest getListRequest;
        
        public getListRequest1() {
        }
        
        public getListRequest1(EdinLib.EdinServiceReference.getListRequest getListRequest) {
            this.getListRequest = getListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.service.org", Order=0)]
        public EdinLib.EdinServiceReference.getListResponse getListResponse;
        
        public getListResponse1() {
        }
        
        public getListResponse1(EdinLib.EdinServiceReference.getListResponse getListResponse) {
            this.getListResponse = getListResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.service.org")]
    public partial class getDocRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediLogin userField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediLogin user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.service.org")]
    public partial class getDocResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediFile resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediFile result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.service.org", Order=0)]
        public EdinLib.EdinServiceReference.getDocRequest getDocRequest;
        
        public getDocRequest1() {
        }
        
        public getDocRequest1(EdinLib.EdinServiceReference.getDocRequest getDocRequest) {
            this.getDocRequest = getDocRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.service.org", Order=0)]
        public EdinLib.EdinServiceReference.getDocResponse getDocResponse;
        
        public getDocResponse1() {
        }
        
        public getDocResponse1(EdinLib.EdinServiceReference.getDocResponse getDocResponse) {
            this.getDocResponse = getDocResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.service.org")]
    public partial class archiveDocRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediLogin userField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediLogin user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.service.org")]
    public partial class archiveDocResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediResponse resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediResponse result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class archiveDocRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.service.org", Order=0)]
        public EdinLib.EdinServiceReference.archiveDocRequest archiveDocRequest;
        
        public archiveDocRequest1() {
        }
        
        public archiveDocRequest1(EdinLib.EdinServiceReference.archiveDocRequest archiveDocRequest) {
            this.archiveDocRequest = archiveDocRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class archiveDocResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.service.org", Order=0)]
        public EdinLib.EdinServiceReference.archiveDocResponse archiveDocResponse;
        
        public archiveDocResponse1() {
        }
        
        public archiveDocResponse1(EdinLib.EdinServiceReference.archiveDocResponse archiveDocResponse) {
            this.archiveDocResponse = archiveDocResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.service.org")]
    public partial class sendDocRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediLogin userField;
        
        private string fileNameField;
        
        private byte[] contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediLogin user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true, Order=2)]
        public byte[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soap.edi.service.org")]
    public partial class sendDocResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ediResponse resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ediResponse result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendDocRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.service.org", Order=0)]
        public EdinLib.EdinServiceReference.sendDocRequest sendDocRequest;
        
        public sendDocRequest1() {
        }
        
        public sendDocRequest1(EdinLib.EdinServiceReference.sendDocRequest sendDocRequest) {
            this.sendDocRequest = sendDocRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendDocResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://soap.edi.service.org", Order=0)]
        public EdinLib.EdinServiceReference.sendDocResponse sendDocResponse;
        
        public sendDocResponse1() {
        }
        
        public sendDocResponse1(EdinLib.EdinServiceReference.sendDocResponse sendDocResponse) {
            this.sendDocResponse = sendDocResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceWsChannel : EdinLib.EdinServiceReference.ServiceWs, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceWsClient : System.ServiceModel.ClientBase<EdinLib.EdinServiceReference.ServiceWs>, EdinLib.EdinServiceReference.ServiceWs {
        
        public ServiceWsClient() {
        }
        
        public ServiceWsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceWsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EdinLib.EdinServiceReference.getDocumentsResponse1 EdinLib.EdinServiceReference.ServiceWs.getDocuments(EdinLib.EdinServiceReference.getDocumentsRequest1 request) {
            return base.Channel.getDocuments(request);
        }
        
        public EdinLib.EdinServiceReference.getDocumentsResponse getDocuments(EdinLib.EdinServiceReference.getDocumentsRequest getDocumentsRequest) {
            EdinLib.EdinServiceReference.getDocumentsRequest1 inValue = new EdinLib.EdinServiceReference.getDocumentsRequest1();
            inValue.getDocumentsRequest = getDocumentsRequest;
            EdinLib.EdinServiceReference.getDocumentsResponse1 retVal = ((EdinLib.EdinServiceReference.ServiceWs)(this)).getDocuments(inValue);
            return retVal.getDocumentsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EdinLib.EdinServiceReference.getDocumentsResponse1> EdinLib.EdinServiceReference.ServiceWs.getDocumentsAsync(EdinLib.EdinServiceReference.getDocumentsRequest1 request) {
            return base.Channel.getDocumentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EdinLib.EdinServiceReference.getDocumentsResponse1> getDocumentsAsync(EdinLib.EdinServiceReference.getDocumentsRequest getDocumentsRequest) {
            EdinLib.EdinServiceReference.getDocumentsRequest1 inValue = new EdinLib.EdinServiceReference.getDocumentsRequest1();
            inValue.getDocumentsRequest = getDocumentsRequest;
            return ((EdinLib.EdinServiceReference.ServiceWs)(this)).getDocumentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EdinLib.EdinServiceReference.uploadDocResponse1 EdinLib.EdinServiceReference.ServiceWs.uploadDoc(EdinLib.EdinServiceReference.uploadDocRequest1 request) {
            return base.Channel.uploadDoc(request);
        }
        
        public EdinLib.EdinServiceReference.uploadDocResponse uploadDoc(EdinLib.EdinServiceReference.uploadDocRequest uploadDocRequest) {
            EdinLib.EdinServiceReference.uploadDocRequest1 inValue = new EdinLib.EdinServiceReference.uploadDocRequest1();
            inValue.uploadDocRequest = uploadDocRequest;
            EdinLib.EdinServiceReference.uploadDocResponse1 retVal = ((EdinLib.EdinServiceReference.ServiceWs)(this)).uploadDoc(inValue);
            return retVal.uploadDocResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EdinLib.EdinServiceReference.uploadDocResponse1> EdinLib.EdinServiceReference.ServiceWs.uploadDocAsync(EdinLib.EdinServiceReference.uploadDocRequest1 request) {
            return base.Channel.uploadDocAsync(request);
        }
        
        public System.Threading.Tasks.Task<EdinLib.EdinServiceReference.uploadDocResponse1> uploadDocAsync(EdinLib.EdinServiceReference.uploadDocRequest uploadDocRequest) {
            EdinLib.EdinServiceReference.uploadDocRequest1 inValue = new EdinLib.EdinServiceReference.uploadDocRequest1();
            inValue.uploadDocRequest = uploadDocRequest;
            return ((EdinLib.EdinServiceReference.ServiceWs)(this)).uploadDocAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EdinLib.EdinServiceReference.archiveDocumentsResponse1 EdinLib.EdinServiceReference.ServiceWs.archiveDocuments(EdinLib.EdinServiceReference.archiveDocumentsRequest1 request) {
            return base.Channel.archiveDocuments(request);
        }
        
        public EdinLib.EdinServiceReference.archiveDocumentsResponse archiveDocuments(EdinLib.EdinServiceReference.archiveDocumentsRequest archiveDocumentsRequest) {
            EdinLib.EdinServiceReference.archiveDocumentsRequest1 inValue = new EdinLib.EdinServiceReference.archiveDocumentsRequest1();
            inValue.archiveDocumentsRequest = archiveDocumentsRequest;
            EdinLib.EdinServiceReference.archiveDocumentsResponse1 retVal = ((EdinLib.EdinServiceReference.ServiceWs)(this)).archiveDocuments(inValue);
            return retVal.archiveDocumentsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EdinLib.EdinServiceReference.archiveDocumentsResponse1> EdinLib.EdinServiceReference.ServiceWs.archiveDocumentsAsync(EdinLib.EdinServiceReference.archiveDocumentsRequest1 request) {
            return base.Channel.archiveDocumentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EdinLib.EdinServiceReference.archiveDocumentsResponse1> archiveDocumentsAsync(EdinLib.EdinServiceReference.archiveDocumentsRequest archiveDocumentsRequest) {
            EdinLib.EdinServiceReference.archiveDocumentsRequest1 inValue = new EdinLib.EdinServiceReference.archiveDocumentsRequest1();
            inValue.archiveDocumentsRequest = archiveDocumentsRequest;
            return ((EdinLib.EdinServiceReference.ServiceWs)(this)).archiveDocumentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EdinLib.EdinServiceReference.getListResponse1 EdinLib.EdinServiceReference.ServiceWs.getList(EdinLib.EdinServiceReference.getListRequest1 request) {
            return base.Channel.getList(request);
        }
        
        public EdinLib.EdinServiceReference.getListResponse getList(EdinLib.EdinServiceReference.getListRequest getListRequest) {
            EdinLib.EdinServiceReference.getListRequest1 inValue = new EdinLib.EdinServiceReference.getListRequest1();
            inValue.getListRequest = getListRequest;
            EdinLib.EdinServiceReference.getListResponse1 retVal = ((EdinLib.EdinServiceReference.ServiceWs)(this)).getList(inValue);
            return retVal.getListResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EdinLib.EdinServiceReference.getListResponse1> EdinLib.EdinServiceReference.ServiceWs.getListAsync(EdinLib.EdinServiceReference.getListRequest1 request) {
            return base.Channel.getListAsync(request);
        }
        
        public System.Threading.Tasks.Task<EdinLib.EdinServiceReference.getListResponse1> getListAsync(EdinLib.EdinServiceReference.getListRequest getListRequest) {
            EdinLib.EdinServiceReference.getListRequest1 inValue = new EdinLib.EdinServiceReference.getListRequest1();
            inValue.getListRequest = getListRequest;
            return ((EdinLib.EdinServiceReference.ServiceWs)(this)).getListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EdinLib.EdinServiceReference.getDocResponse1 EdinLib.EdinServiceReference.ServiceWs.getDoc(EdinLib.EdinServiceReference.getDocRequest1 request) {
            return base.Channel.getDoc(request);
        }
        
        public EdinLib.EdinServiceReference.getDocResponse getDoc(EdinLib.EdinServiceReference.getDocRequest getDocRequest) {
            EdinLib.EdinServiceReference.getDocRequest1 inValue = new EdinLib.EdinServiceReference.getDocRequest1();
            inValue.getDocRequest = getDocRequest;
            EdinLib.EdinServiceReference.getDocResponse1 retVal = ((EdinLib.EdinServiceReference.ServiceWs)(this)).getDoc(inValue);
            return retVal.getDocResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EdinLib.EdinServiceReference.getDocResponse1> EdinLib.EdinServiceReference.ServiceWs.getDocAsync(EdinLib.EdinServiceReference.getDocRequest1 request) {
            return base.Channel.getDocAsync(request);
        }
        
        public System.Threading.Tasks.Task<EdinLib.EdinServiceReference.getDocResponse1> getDocAsync(EdinLib.EdinServiceReference.getDocRequest getDocRequest) {
            EdinLib.EdinServiceReference.getDocRequest1 inValue = new EdinLib.EdinServiceReference.getDocRequest1();
            inValue.getDocRequest = getDocRequest;
            return ((EdinLib.EdinServiceReference.ServiceWs)(this)).getDocAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EdinLib.EdinServiceReference.archiveDocResponse1 EdinLib.EdinServiceReference.ServiceWs.archiveDoc(EdinLib.EdinServiceReference.archiveDocRequest1 request) {
            return base.Channel.archiveDoc(request);
        }
        
        public EdinLib.EdinServiceReference.archiveDocResponse archiveDoc(EdinLib.EdinServiceReference.archiveDocRequest archiveDocRequest) {
            EdinLib.EdinServiceReference.archiveDocRequest1 inValue = new EdinLib.EdinServiceReference.archiveDocRequest1();
            inValue.archiveDocRequest = archiveDocRequest;
            EdinLib.EdinServiceReference.archiveDocResponse1 retVal = ((EdinLib.EdinServiceReference.ServiceWs)(this)).archiveDoc(inValue);
            return retVal.archiveDocResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EdinLib.EdinServiceReference.archiveDocResponse1> EdinLib.EdinServiceReference.ServiceWs.archiveDocAsync(EdinLib.EdinServiceReference.archiveDocRequest1 request) {
            return base.Channel.archiveDocAsync(request);
        }
        
        public System.Threading.Tasks.Task<EdinLib.EdinServiceReference.archiveDocResponse1> archiveDocAsync(EdinLib.EdinServiceReference.archiveDocRequest archiveDocRequest) {
            EdinLib.EdinServiceReference.archiveDocRequest1 inValue = new EdinLib.EdinServiceReference.archiveDocRequest1();
            inValue.archiveDocRequest = archiveDocRequest;
            return ((EdinLib.EdinServiceReference.ServiceWs)(this)).archiveDocAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EdinLib.EdinServiceReference.sendDocResponse1 EdinLib.EdinServiceReference.ServiceWs.sendDoc(EdinLib.EdinServiceReference.sendDocRequest1 request) {
            return base.Channel.sendDoc(request);
        }
        
        public EdinLib.EdinServiceReference.sendDocResponse sendDoc(EdinLib.EdinServiceReference.sendDocRequest sendDocRequest) {
            EdinLib.EdinServiceReference.sendDocRequest1 inValue = new EdinLib.EdinServiceReference.sendDocRequest1();
            inValue.sendDocRequest = sendDocRequest;
            EdinLib.EdinServiceReference.sendDocResponse1 retVal = ((EdinLib.EdinServiceReference.ServiceWs)(this)).sendDoc(inValue);
            return retVal.sendDocResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EdinLib.EdinServiceReference.sendDocResponse1> EdinLib.EdinServiceReference.ServiceWs.sendDocAsync(EdinLib.EdinServiceReference.sendDocRequest1 request) {
            return base.Channel.sendDocAsync(request);
        }
        
        public System.Threading.Tasks.Task<EdinLib.EdinServiceReference.sendDocResponse1> sendDocAsync(EdinLib.EdinServiceReference.sendDocRequest sendDocRequest) {
            EdinLib.EdinServiceReference.sendDocRequest1 inValue = new EdinLib.EdinServiceReference.sendDocRequest1();
            inValue.sendDocRequest = sendDocRequest;
            return ((EdinLib.EdinServiceReference.ServiceWs)(this)).sendDocAsync(inValue);
        }
    }
}
